const products  = [
    {
        title: 'Producto 1',
        description: 'Descripción del Producto 1',
        price: 10,
        thumbnail: 'imagen1.jpg',
        code: 'code1',
        stock: 100,
    },
    {
        title: 'Producto 2',
        description: 'Descripción del Producto 2',
        price: 20,
        thumbnail: 'imagen2.jpg',
        code: 'code2',
        stock: 50,
    },
    {
        title: 'Producto 3',
        description: 'Descripción del Producto 3',
        price: 15,
        thumbnail: 'imagen3.jpg',
        code: 'code3',
        stock: 75,
    },
    {
        title: 'Producto 4',
        description: 'Descripción del Producto 4',
        price: 25,
        thumbnail: 'imagen4.jpg',
        code: 'code4',
        stock: 60,
    },
    {
        title: 'Producto 5',
        description: 'Descripción del Producto 5',
        price: 30,
        thumbnail: 'imagen5.jpg',
        code: 'code5',
        stock: 80,
    },
    {
        title: 'Producto 6',
        description: 'Descripción del Producto 6',
        price: 18,
        thumbnail: 'imagen6.jpg',
        code: 'code6',
        stock: 90,
    },
    {
        title: 'Producto 7',
        description: 'Descripción del Producto 7',
        price: 12,
        thumbnail: 'imagen7.jpg',
        code: 'code7',
        stock: 120,
    },
    {
        title: 'Producto 8',
        description: 'Descripción del Producto 8',
        price: 22,
        thumbnail: 'imagen8.jpg',
        code: 'code8',
        stock: 40,
    },
    {
        title: 'Producto 9',
        description: 'Descripción del Producto 9',
        price: 28,
        thumbnail: 'imagen9.jpg',
        code: 'code9',
        stock: 70,
    },
    {
        title: 'Producto 10',
        description: 'Descripción del Producto 10',
        price: 14,
        thumbnail: 'imagen10.jpg',
        code: 'code10',
        stock: 110,
    },
];

module.exports = products;
